### ISSUE TITLE
"无法发送具有此谓词类型的内容正文。

### ISSUE THREAD

**Issue by sitsh** [jpush/jmessage-api-csharp-client#1]
vs 2017 15.7.2
framework 4.6.1

restapi 接口 地址

[https://report.im.jpush.cn/v2/messages?count=500&begin_time=2015-11-02 10:10:10&end_time=2015-11-02 10:10:12](https://report.im.jpush.cn/v2%2Fmessages%3Fcount%3D10%26begin_time%3D2017-11-20+00%3A00%3A00%26end_time%3D2018-05-23+08%3A12%3A47)

`public async Task<HttpResponse> GetMessageHistoryAsync(int count, string beginTime, string endTime)
`
 

```
var request = new HttpRequestMessage(HttpMethod.Get, url)
            {
                Content =  new StringContent(string.Empty, Encoding.UTF8, "application/json")
                
            };

            HttpResponseMessage httpResponseMessage = await httpClient.SendAsync(request).ConfigureAwait(false);
            string content = await httpResponseMessage.Content.ReadAsStringAsync().ConfigureAwait(false);
            return new HttpResponse(httpResponseMessage.StatusCode, httpResponseMessage.Headers, content);
```

网上查了好像是因为 httpclient get 方法 不能发送 Content  有值的数据
如果注释 

`//Content =  new StringContent(string.Empty, Encoding.UTF8, "application/json")`

这行代码 又因为 Content 没有设置 application/json  返回 404 结果

**Comment by ghost** [comment]
确实是这样的，这是我们 API 那边的问题，最新版本的 csharp sdk 已解决这个问题了
